In [12]:
#gives the computers ability to understand text and spoken words like humans do

#processes involved are
## speech recognition
## POS (part of speech) tagging
##named entity recognition(NER)
##sentiment analysis
##natural language generation(NLG)

#We use nltk(natural language tool kit library)

#nlp preprocesssing is really difficult,since the sentences and paragraphs are different sizes and the should be converted to numerical value

#there are different text preprocessing methods like:
#tokenization,stemming,lemmatization,stop word removal

In [2]:
#pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in c:\users\user\appdata\roaming\python\python312\site-packages (3.8.1)
Requirement already satisfied: click in c:\users\user\appdata\roaming\python\python312\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\user\appdata\roaming\python\python312\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\user\appdata\roaming\python\python312\site-packages (from nltk) (2024.5.15)
Requirement already satisfied: tqdm in c:\users\user\appdata\roaming\python\python312\site-packages (from nltk) (4.66.4)
Requirement already satisfied: colorama in c:\users\user\appdata\roaming\python\python312\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import nltk

# Tokenization

In [4]:
#punkt is an unsupervised machine learning model provided by nltk library in python to perform tokenization
#triple quotes-docstring,u can use enter and use spaces

In [5]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [6]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [7]:
text=''' Tokenization breaks down a text into individual units.
It can be words, phrases,sentences,or other meaningful elements.'''
word_tokenize(text)

['Tokenization',
 'breaks',
 'down',
 'a',
 'text',
 'into',
 'individual',
 'units',
 '.',
 'It',
 'can',
 'be',
 'words',
 ',',
 'phrases',
 ',',
 'sentences',
 ',',
 'or',
 'other',
 'meaningful',
 'elements',
 '.']

In [8]:
sent_tokenize(text) #sentences

[' Tokenization breaks down a text into individual units.',
 'It can be words, phrases,sentences,or other meaningful elements.']

# stemming

In [9]:
from nltk.stem import PorterStemmer

text='He captures beautiful pictures'
words=word_tokenize(text)
ps=PorterStemmer()
for w in words:
    print('original word:',w)
    print('stemmed word:',ps.stem(w))

original word: He
stemmed word: he
original word: captures
stemmed word: captur
original word: beautiful
stemmed word: beauti
original word: pictures
stemmed word: pictur

# lemmatization

In [ ]:
#to overcome the disadvantages of stemming we use lemmatization

In [10]:
#nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...

True

In [11]:
from nltk.stem import WordNetLemmatizer
wnl=WordNetLemmatizer()

for w in words:
    print('original word:',w)
    print('lemmatizeded word:',wnl.lemmatize(w))

original word: He
lemmatizeded word: He
original word: captures
lemmatizeded word: capture
original word: beautiful
lemmatizeded word: beautiful
original word: pictures
lemmatizeded word: picture

# stop word removal

In [13]:
#nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [14]:
from nltk.corpus import stopwords
stop_words=stopwords.words('english')
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

In [16]:
example_sent='An apple a day keeps the diseases at bay.'
example_sent=example_sent.lower() # to match it with the list of stop words,where all words are lower case
word_tokens=word_tokenize(example_sent)

for word in word_tokens:
    if word not in stop_words:
        print(word,end=' ')

apple day keeps diseases bay .

In [ ]:
#word embedding techniques-used to convert text into numeric data
#different techniques are BoW,

# BoW-bag of words

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
Sentences=['We are using the Bag of Word model',
          'Bag of Word model is used for extracting the features.']

In [20]:
cv=CountVectorizer()
features_text=cv.fit_transform(Sentences).toarray()
print(cv.vocabulary_)

{'we': 11, 'are': 0, 'using': 10, 'the': 8, 'bag': 1, 'of': 7, 'word': 12, 'model': 6, 'is': 5, 'used': 9, 'for': 4, 'extracting': 2, 'features': 3}

In [21]:
cv.get_feature_names_out()

array(['are', 'bag', 'extracting', 'features', 'for', 'is', 'model', 'of',
       'the', 'used', 'using', 'we', 'word'], dtype=object)

In [22]:
features_text

array([[1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1]], dtype=int64)

In [23]:
import pandas as pd

In [24]:
pd.DataFrame(features_text,columns=cv.get_feature_names_out())

,are,bag,extracting,features,for,is,model,of,the,used,using,we,word
0,1,1,0,0,0,0,1,1,1,0,1,1,1
1,0,1,1,1,1,1,1,1,1,1,0,0,1

# TF-IDF(Term Frequency-Inverse Document Frequency)

In [ ]:
#TF- MEASURES HOW OFTEN A TERM APPEARS IN A DOCUMENT.
#IDF-MEASURES HOW UNIQUE OR RARE A TERM IS ACROSS ALL DOCUMENTS.
#Higher the TF-IDF value ,more important the term is in the context

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [27]:
corpus=[
    'Machine learning is fascinating.',
    'Natural Language Processing is a subfield of AI.',
    'Machine Learning and Natural Language Processing are usrd in many applications.'
]

vectorizer=TfidfVectorizer()
tfidf_matrix=vectorizer.fit_transform(corpus)
feature_names=vectorizer.get_feature_names_out()

In [28]:
df_tfidf=pd.DataFrame(data=tfidf_matrix.toarray(),columns=feature_names)
df_tfidf

,ai,and,applications,are,fascinating,in,is,language,learning,machine,many,natural,of,processing,subfield,usrd
0,0.000000,0.000000,0.000000,0.000000,0.604652,0.000000,0.459854,0.000000,0.459854,0.459854,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.433816,0.000000,0.000000,0.000000,0.000000,0.000000,0.329928,0.329928,0.000000,0.000000,0.000000,0.329928,0.433816,0.329928,0.433816,0.000000
2,0.000000,0.335352,0.335352,0.335352,0.000000,0.335352,0.000000,0.255044,0.255044,0.255044,0.335352,0.255044,0.000000,0.255044,0.000000,0.335352